"""Added private_key column to User model

Revision ID: c9cb048391eb
Revises: 07e900ab75a3
Create Date: 2024-07-04 16:49:56.425028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cb048391eb'
down_revision = '07e900ab75a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('private_key')

    # ### end Alembic commands ###
