"""empty message

Revision ID: f655e50e3bed
Revises: c9cb048391eb
Create Date: 2024-07-05 11:52:38.755471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f655e50e3bed'
down_revision = 'c9cb048391eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaintext_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('plaintext_content')

    # ### end Alembic commands ###
